{
    "vegetables": [
        {"name":"Artiskok", "syre":4.31, "base":0},
        {"name":"Asparges", "syre":1.01, "base":0},
        {"name":"Bønner (tørrede)", "syre":9.70, "base":0},
        {"name":"Linser", "syre":17.80, "base":0},
        {"name":"Sojabønner", "syre":26.58, "base":0},
        {"name":"Ærter, tørrede", "syre":3.41, "base":0},

        {"name":"Agurk", "syre":0, "base":31.50},
        {"name":"Blomkål", "syre":0, "base":3.04},
        {"name":"Brøndkarse", "syre":0, "base":7.72},
        {"name":"Bønner (friske)", "syre":0, "base":8.71},
        {"name":"Cikorie (julesalat)", "syre":0, "base":2.33},
        {"name":"Dild", "syre":0, "base":18.36},
        {"name":"Grønkål", "syre":0, "base":4.00},
        {"name":"Græskar", "syre":0, "base":0.28},
        {"name":"Gulerødder", "syre":0, "base":10.00},
        {"name":"Hovedsalat", "syre":0, "base":14.12},
        {"name":"Hvidkål", "syre":0, "base":4.02},
        {"name":"Kartofler, hvide", "syre":0, "base":5.90},
        {"name":"Kålrabi", "syre":0, "base":5.99},
        {"name":"Løvetand", "syre":0, "base":22.72},
        {"name":"Majroer", "syre":0, "base":10.18},
        {"name":"Peberrod m. skal", "syre":0, "base":2.72},
        {"name":"Porrer", "syre":0, "base":11.00},
        {"name":"Radiser", "syre":0, "base":6.05},
        {"name":"Rosenkål", "syre":0, "base":6.03},
        {"name":"Rødbeder", "syre":0, "base":11.37},
        {"name":"Rødkål", "syre":0, "base":2.20},
        {"name":"Rødløg", "syre":0, "base":2.94},
        {"name":"Selleri", "syre":0, "base":11.33},
        {"name":"Sort ræddike, m. skal", "syre":0, "base":39.40},
        {"name":"Sukkerroer", "syre":0, "base":9.37},
        {"name":"Tomat", "syre":0, "base":13.67},
        {"name":"Vandmelon", "syre":0, "base":1.83},
        {"name":"Ærter, grøn- (unge, friske)", "syre":0, "base":5.15},

        {"name":"Agurk", "syre":0, "base":32},
	    {"name":"Blomkål", "syre":0, "base":5},
	    {"name":"Broccoli", "syre":0, "base":4},
	    {"name":"Bønner, brune", "syre":9, "base":0},
	    {"name":"Bønner, grønne", "syre":0, "base":8},
	    {"name":"Bønner, hvide", "syre":10, "base":0},
	    {"name":"Champignon", "syre":0, "base":2},
	    {"name":"Dild", "syre":0, "base":18},
	    {"name":"Endivie", "syre":0, "base":14},
	    {"name":"Græskar", "syre":0, "syre":0,"base":3},
	    {"name":"Grønkål", "syre":0, "base":4},
	    {"name":"Gulerødder", "syre":0, "base":11},
	    {"name":"Hestebønner", "syre":9, "base":0},
	    {"name":"Hovedsalat", "syre":0, "base":14},
	    {"name":"Kantereller", "syre":0, "base":4},
	    {"name":"Karse", "syre":0, "base":8},
	    {"name":"Kartofler", "syre":0, "base":6},
	    {"name":"Korender", "syre":0, "base":8},
	    {"name":"Kål, hvid", "syre":0, "base":4},
	    {"name":"Kål, rød", "syre":0, "base":2},
	    {"name":"Kålrabi", "syre":0, "base":6},
	    {"name":"Kålrabiblade", "syre":0, "base":19},
	    {"name":"Linser", "syre":18, "base":0},
	    {"name":"Løg", "syre":0, "base":3},
	    {"name":"Løventandsblade", "syre":0, "base":23},
	    {"name":"Majs", "syre":5, "base":0},
	    {"name":"Pastinak", "syre":0, "base":7},
	    {"name":"Peberrod", "syre":0, "base":3},
	    {"name":"Persille", "syre":0, "base":0},
	    {"name":"Porre", "syre":0, "base":4},
		{"name":"Purløg", "syre":0, "base":8},
		{"name":"Rosenkål", "syre":0, "base":1},
		{"name":"Ræddiker", "syre":0, "base":6},
	    {"name":"Rødbeder", "syre":0, "base":11},
	    {"name":"Salat", "syre":0, "base":7},
	    {"name":"Savoykål", "syre":0, "base":5},
	    {"name":"Selleri, rod", "syre":0, "base":11},
	    {"name":"Selleri, stængel, blade", "syre":0, "base":13},
	    {"name":"Skorzonerrod", "syre":0, "base":2},
	    {"name":"Snitbønner", "syre":0, "base":9},
	    {"name":"Spidskål", "syre":0, "base":9},
	    {"name":"Spinat", "syre":0, "base":13},
	    {"name":"Solbær", "syre":0, "base":3},
	    {"name":"Sukkerærter", "syre":0, "base":5},
	    {"name":"Syre-blade", "syre":0, "base":11},
	    {"name":"Ærter, gule tørrede", "syre":5, "base":0},
	    {"name":"Ærter, spirede", "syre":0, "base":5}
    ],

    "fruit" : [
        {"name":"Abrikoser", "syre":0, "base":4.79},
        {"name":"Ananas", "syre":0, "base":3.59},
        {"name":"Appelsiner", "syre":0, "base":9.61},
        {"name":"Bananer", "syre":0, "base":4.38},
        {"name":"Blommer", "syre":0, "base":3.99},
        {"name":"Brombær", "syre":0, "base":7.14},
        {"name":"Dadler, tørrede", "syre":0, "base":5.50},
        {"name":"Druer", "syre":0, "base":7.15},
        {"name":"Ferskner", "syre":0, "base":5.40},
        {"name":"Figner, tørrede", "syre":0, "base":27.81},
        {"name":"Hindbær", "syre":0, "base":5.19},
        {"name":"Jordbær", "syre":0, "base":1.76},
        {"name":"Kirsebær, sure", "syre":0, "base":2.08},
        {"name":"Kirsebær, søde", "syre":0, "base":4.33},
        {"name":"Mandariner", "syre":0, "base":11.77},
        {"name":"Pærer", "syre":0, "base":3.26},
        {"name":"Ribs", "syre":0, "base":1.10},
        {"name":"Rosiner", "syre":0, "base":15.10},
        {"name":"Solbær", "syre":0, "base":3.16},
        {"name":"Stikkelsbær", "syre":0, "base":5.92},
        {"name":"Svesker", "syre":0, "base":3.99},
        {"name":"Æbler", "syre":0, "base":1.38},

        {"name":"Abrikoser, tørrede", "syre":0, "base":5},
	    {"name":"Ananas", "syre":0, "base":5},
	    {"name":"Appelsin", "syre":0, "base":6},
	    {"name":"Asparges", "syre":0, "base":1},
	    {"name":"Bananer", "syre":0, "base":5},
	    {"name":"Blommer", "syre":0, "base":6},
	    {"name":"Blåbær", "syre":0, "base":5},
	    {"name":"Brombær", "syre":0, "base":8},
	    {"name":"Citroner", "syre":0, "base":5},
	    {"name":"Dadler", "syre":0, "base":6},
	    {"name":"Ferskner", "syre":0, "base":5},
	    {"name":"Figner, friske", "syre":0, "base":6},
	    {"name":"Figner, tørrede", "syre":0, "base":28},
	    {"name":"Grapefrugt", "syre":0, "base":6},
	    {"name":"Hyben, tørrede", "syre":0, "base":15},
	    {"name":"Hyldebær", "syre":0, "base":0},
	    {"name":"Jordbær", "syre":0, "base":3},
	    {"name":"Kirsebær", "syre":0, "base":4},
	    {"name":"Kastanier", "syre":0, "base":12},
	    {"name":"Mandariner", "syre":0, "base":19},
	    {"name":"Melon", "syre":0, "base":7},
	    {"name":"Rabarber", "syre":0, "base":6},
	    {"name":"Ribs, hvide", "syre":0, "base":6},
	    {"name":"Ribs, røde", "syre":0, "base":3},
	    {"name":"Rosiner", "syre":0, "base":23},
	    {"name":"Stikkelsbær, grønne", "syre":0, "base":8},
	    {"name":"Stikkelsbær, røde", "syre":0, "base":10},
	    {"name":"Svesker", "syre":0, "base":15},
	    {"name":"Tyttebær", "syre":0, "base":5},
	    {"name":"Vindruer", "syre":0, "base":7},
	    {"name":"Æbler", "syre":0, "base":2}

    ],

    "corn" : [

        {"name":"Boghvedegryn", "syre":3.77, "base":0},
        {"name":"Byg, afskallet", "syre":10.58, "base":0},
        {"name":"Grahamsbrød", "syre":6.13, "base":0},
        {"name":"Havre, afskallet", "syre":2.58, "base":0},
        {"name":"Havregryn", "syre":9.98, "base":0},
        {"name":"Havremel", "syre":14.50, "base":0},
        {"name":"Hirse, afskallet", "syre":0.86, "base":0},
        {"name":"Hvede, afskallet", "syre":8.32, "base":0},
        {"name":"Hvede, hel", "syre":2.66, "base":0},
        {"name":"Hvidt brød", "syre":10.99, "base":0},
        {"name":"Kager af hvidt mel", "syre":12.31, "base":0},
        {"name":"Makaroni", "syre":5.11, "base":0},
        {"name":"Majsmel", "syre":6.45, "base":0},
        {"name":"Ris (med sølvhinden)", "syre":39.13, "base":0},
        {"name":"Ris, afskallet (rød ris)", "syre":17.96, "base":0},
        {"name":"Rug, hel", "syre":11.31, "base":0},
        {"name":"Rugbrød", "syre":8.54, "base":0},
        {"name":"Rugmel", "syre":16.49, "base":0},
        {"name":"Tvebakker", "syre":10.41, "base":0},


        {"name":"Pumpernickelbrød", "syre":0, "base":4.28}
    ],

    
    "nuts":[

        {"name":"Hasselnødder", "syre":0.2, "base":0},
        {"name":"Jordnødder", "syre":12.7, "base":0},
        {"name":"Mandler", "syre":2.1, "base":0},
        {"name":"Valnødder", "syre":7.72, "base":0},

        {"name":"Bog (bøgens frugt)", "syre":0, "base":40.51},
        {"name":"Kastanier", "syre":0, "base":9.62},
        {"name":"Kokosnødder", "syre":0, "base":4.09},
        {"name":"Byggryn", "syre":11, "base":0},
	    {"name":"Franskbrød", "syre":11, "base":0},
	    {"name":"Havregryn,-mel", "syre":13, "base":0},
	    {"name":"Helkornsbrød", "syre":6, "base":0},
	    {"name":"Hvede, graham", "syre":17, "base":0},
	    {"name":"Hvede, hel", "syre":39, "base":0},
	    {"name":"Hvedemel, fin", "syre":11, "base":0},
	    {"name":"Klid, hvede", "syre":47, "base":0},
	    {"name":"Klid, rug", "syre":47, "base":0},
	    {"name":"Knækbrød, rug", "syre":7, "base":0},
	    {"name":"Makaroni", "syre":5, "base":0},
	    {"name":"Ris, brune", "syre":40, "base":0},
	    {"name":"Ris, polerede", "syre":8, "base":0},
	    {"name":"Rugbrød", "syre":7, "base":0},
	    {"name":"Rugmel, fint", "syre":11, "base":0},
	    {"name":"Rugmel, groft", "syre":16, "base":0},
	    {"name":"Hasselnødder", "syre":1, "base":0},
	    {"name":"Kokosnød", "syre":0, "base":4},
	    {"name":"Mandler", "syre":1, "base":0},
	    {"name":"Paranødder", "syre":18, "base":0},
	    {"name":"Valnødder", "syre":8, "base":0},
	    {"name":"Voksbønner", "syre":0, "base":4},
	    {"name":"Oliven", "syre":0, "base":35}
    ],

    
    "milk" : [

        {"name":"Fløde 30 %", "syre":2.00, "base":0},
        {"name":"Kvark", "syre":17.30, "base":0},
        {"name":"Schweizerost", "syre":17.49, "base":0},
        {"name":"Smør", "syre":4.3, "base":0},

        {"name":"Gedemælk", "syre":0, "base":2.40},
        {"name":"Komælk", "syre":0, "base":2.95},
        {"name":"Modermælk", "syre":0, "base":2.25},
        {"name":"Skummetmælk", "syre":0, "base":3.89},
        {"name":"Fløde, 13%", "syre":0, "base":2},
	    {"name":"Fløde, 38%", "syre":3, "base":0},
	    {"name":"Gedemælk", "syre":0, "syre":0,"base":6},
	    {"name":"Myseost", "syre":0, "base":4},
	    {"name":"Mælk, homogeniseret", "syre":4, "base":0},
	    {"name":"Mælk, ukogt, sommer", "syre":0, "base":3},
	    {"name":"Mælk, ukogt, vinter", "syre":0, "base":3},
	    {"name":"Mælk, uskummet, sommer", "syre":0, "base":3},
	    {"name":"Nælde", "syre":0, "base":35},
	    {"name":"Ost, 20%", "syre":5, "base":0},
	    {"name":"Ost, 30%", "syre":10, "base":0},
	    {"name":"Ost, 45%", "syre":17, "base":0},
	    {"name":"Pumpernickel", "syre":6, "base":0}
    ],

    "fish" : [

        {"name":"Hvid fisk (gedde)", "syre":2.75, "base":0},
        {"name":"Laks", "syre":8.33, "base":0},
        {"name":"Sild, saltet", "syre":17.35, "base":0},
        {"name":"Skaldyr", "syre":19.52, "base":0},

        {"name":"Østers", "syre":0, "base":10.25},
        {"name":"Flynder", "syre":13, "base":0},
	    {"name":"Hellefisk", "syre":18, "base":0},
	    {"name":"Laks", "syre":8, "base":0},
	    {"name":"Makrel", "syre":10, "base":0},
	    {"name":"Rogn, torske", "syre":35, "base":0},
	    {"name":"Sild", "syre":13, "base":0},
	    {"name":"Torsk, fersk", "syre":17, "base":0},
	    {"name":"Ørred", "syre":20, "base":0},
	    {"name":"Ål", "syre":10, "base":0}
    ],


   	"egg":[
   
   		{"name":"Æg, hele", "syre":24.47, "base":0},
        {"name":"Æg, blommen", "syre":51.83, "base":0},
        {"name":"Æg, hviden", "syre":8.2, "base":0},

        {"name":"Æg, blomme", "syre":49, "base":0},
	    {"name":"Æg, hele", "syre":24, "base":0},
	    {"name":"Æg, hvide", "syre":8, "base":0}
   	],
    
    "meat":[

        {"name":"And", "syre":20, "base":0},
        {"name":"Bacon", "syre":9.90, "base":0},
        {"name":"Fårekød", "syre":20.30, "base":0},
        {"name":"Kalvekød", "syre":22.96, "base":0},
        {"name":"Kanin", "syre":22.36, "base":0},
        {"name":"Kylling", "syre":24.32, "base":0},
        {"name":"Oksekød", "syre":38.61, "base":0},
        {"name":"Oksetunge", "syre":10.60, "base":0},
        {"name":"Røget skinke", "syre":6.95, "base":0},
        {"name":"Svinekød", "syre":12.4, "base":0},
        {"name":"Blod af dyr (gennemsnit)", "syre":0, "base":5.49},
        {"name":"And", "syre":20, "base":0},
	    {"name":"Due", "syre":20, "base":0},
	    {"name":"Fårekød, fedt", "syre":20, "base":0},
	    {"name":"Fårekød, magert", "syre":17, "base":0},
	    {"name":"Gås", "syre":25, "base":0},
	    {"name":"Hare", "syre":25, "base":0},
	    {"name":"Kalvekød, fedt", "syre":25, "base":0},
	    {"name":"Kalvekød, magert", "syre":17, "base":0},
	    {"name":"Kalvenyre", "syre":15, "base":0},
	    {"name":"Kylling", "syre":25, "base":0},
	    {"name":"Lever, okse", "syre":40, "base":0},
	    {"name":"Oksekød, magert", "syre":14, "base":0},
	    {"name":"Oksekød, middelfedt", "syre":37, "base":0},
	    {"name":"Oksetunge", "syre":15, "base":0},
	    {"name":"Svinekød, magert", "syre":12, "base":0},
	    {"name":"Svinekød, middelfedt", "syre":13, "base":0}
    ],

    "drinks": [

        {"name":"Chokolade", "syre":8.10, "base":0},
        {"name":"Øl", "syre":0.2, "base":0},

        {"name":"Appelsinsaft", "syre":0, "base":10},
        {"name":"Druesaft", "syre":0, "base":5.16},
        {"name":"Skummetmælk", "syre":0, "base":3.89},
        {"name":"Sødmælk", "syre":0, "base":2.95},
        {"name":"Vin", "syre":0, "base":0.59},
        {"name":"Appelsinsaft", "syre":0, "base":10},
	    {"name":"Øl", "syre":0.2, "base":0}
    ],

    "misc": [
    	{"name":"Farin", "syre":0, "base":0},
	    {"name":"Honning", "syre":1, "base":0}
	]
}